spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/picturehandle
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.mybatis.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8081